backbone.first_channels:
  chosen: 16
backbone.last_channels:
  chosen: 1280
backbone.layers.1.kernel_size:
  chosen: 3
backbone.layers.1.expand_ratio:
  chosen: 1
backbone.layers.1.depth:
  chosen: 1
backbone.layers.1.out_channels:
  chosen: 16
backbone.layers.2.kernel_size:
  chosen: 3
backbone.layers.2.expand_ratio:
  chosen: 3
backbone.layers.2.depth:
  chosen: 2
backbone.layers.2.out_channels:
  chosen: 24
backbone.layers.3.kernel_size:
  chosen: 5
backbone.layers.3.expand_ratio:
  chosen: 3
backbone.layers.3.depth:
  chosen: 2
backbone.layers.3.out_channels:
  chosen: 40
backbone.layers.4.kernel_size:
  chosen: 7
backbone.layers.4.expand_ratio:
  chosen: 4
backbone.layers.4.depth:
  chosen: 2
backbone.layers.4.out_channels:
  chosen: 80
backbone.layers.5.kernel_size:
  chosen: 5
backbone.layers.5.expand_ratio:
  chosen: 3
backbone.layers.5.depth:
  chosen: 2
backbone.layers.5.out_channels:
  chosen: 112
backbone.layers.6.kernel_size:
  chosen: 3
backbone.layers.6.expand_ratio:
  chosen: 6
backbone.layers.6.depth:
  chosen: 2
backbone.layers.6.out_channels:
  chosen: 160
input_shape:
  chosen:
  - 224
  - 224
